# Generated by Django 6.0.7 on 2026-07-25 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name in Bengali', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version', unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief category description')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name in Bengali', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Poem title in Bengali', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField(help_text='The poem content')),
                ('english_translation', models.TextField(blank=True, help_text='Optional English translation')),
                ('pen_note', models.TextField(blank=True, help_text='লেখনীর কথা - Your inspiration behind this poem')),
                ('featured_image', models.ImageField(blank=True, help_text='Cover image for the poem', null=True, upload_to='poem_images/')),
                ('audio_file', models.FileField(blank=True, help_text='Audio recitation (MP3 format)', null=True, upload_to='poem_audio/')),
                ('is_published', models.BooleanField(default=False, help_text='Publish this poem')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poems', to='poems.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='poems', to='poems.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='poems.poem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='poems.poem')),
            ],
            options={
                'unique_together': {('poem', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='poem',
            index=models.Index(fields=['-published_at'], name='poems_poem_publish_c4e8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='poem',
            index=models.Index(fields=['author'], name='poems_poem_author__9f90fc_idx'),
        ),
        migrations.AddIndex(
            model_name='poem',
            index=models.Index(fields=['category'], name='poems_poem_categor_849ca7_idx'),
        ),
    ]
