# Generated by Django 6.0.7 on 2026-07-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='english_translation',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='pen_note',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='poem_audio/'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='poem',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='poem_images/'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poem',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
