# Generated by Django 6.0.7 on 2026-07-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_remove_poem_tags_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='featured_image',
        ),
    ]
